### ISSUE TITLE
Missing terrain tile

### ISSUE THREAD

**Issue by jschleuss** [datadesk/web-map-maker#193]
There's a missing terrain tile in the East Bay at zoom level 8

![la-mapmaker-12-11-2018-28-17-46](https://user-images.githubusercontent.com/695934/49838618-5801c980-fd60-11e8-8564-ba4ad72a89b6.png)

Issue does not show up in live interactive Nextzen maps that we've pubbed

![screen shot 2018-12-11 at 4 18 30 pm](https://user-images.githubusercontent.com/695934/49838643-75369800-fd60-11e8-86fe-0d24f2ba482a.png)

**Comment by ewagstaff** [comment]
Zero idea why, but this issue disappears when the tiles are fetched as GeoJSON:

```
nextzen:
        type: GeoJSON
        url: https://{s}.tiles.nextzen.org/tilezen/vector/v1/256/all/{z}/{x}/{y}.json
        url_params:
            api_key: global.sdk_mapzen_api_key
        url_subdomains: [a,b,c,d]
        rasters: [normals]
        max_zoom: 16
```

Any disadvantage of handling this way?
